# Generated by Django 2.2.2 on 2019-07-19 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SoMPortal', '0003_semestergrade_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SoMPortal.Student'),
            preserve_default=False,
        ),
    ]
