# Generated by Django 2.2.2 on 2019-07-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoMPortal', '0004_test_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestergrade',
            name='test',
        ),
        migrations.AddField(
            model_name='semestergrade',
            name='test',
            field=models.ManyToManyField(to='SoMPortal.Test'),
        ),
    ]
