# Generated by Django 2.2.2 on 2019-07-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoMPortal', '0005_auto_20190719_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestergrade',
            name='semester',
            field=models.CharField(choices=[('1st sem', '1st Semester'), ('2nd sem', '2nd Semester'), ('3rd sem', '3rd Semester'), ('4th sem', '4th Semester'), ('5th sem', '5th Semester'), ('6th sem', '6th Semester'), ('7th sem', '7th Semester'), ('8th sem', '8th Semester')], max_length=12),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('Unit 1', 'Unit Test 1'), ('Unit 2', 'Unit Test 2'), ('Lab 1', 'Lab Test 1'), ('Lab 2', 'Lab Test 2'), ('Final', 'Final Test')], max_length=10),
        ),
    ]
